#!/bin/bash

# --- basic apts
sudo apt install software-properties-common
sudo add-apt-repository universe

# --- ros
sudo apt update && sudo apt install curl -y
sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

sudo apt update
sudo apt upgrade
sudo apt install ros-foxy-desktop python3-argcomplete python3-colcon-common-extensions ros-dev-tools python3-bloom python3-rosdep fakeroot debhelper dh-python

# --- rosdep
sudo rosdep init
rosdep update --include-eol-distros

# --- slam toolbox
sudo apt install ros-foxy-slam-toolbox

# --- nav2
sudo apt install ros-foxy-navigation2
sudo apt install ros-foxy-nav2-bringup

# --- turtle bot
sudo apt install ros-foxy-turtlebot3-gazebo
