#!/bin/bash

gnome-terminal --tab -- bash -c 'source /opt/ros/foxy/setup.bash;
                                source /home/$(whoami)/GalacticRacing/sim_ws/install/setup.bash;
                                cd /home/$(whoami)/GalacticRacing/sim_ws;
                                colcon build --packages-select pure_pursuit;
                                rviz2;
                                exec bash'

sleep 3

gnome-terminal --tab -- bash -c 'ros2 launch f1tenth_gym_ros gym_bridge_launch.py;
                                exec bash'

sleep 3

gnome-terminal --tab -- bash -c 'ros2 launch particle_filter localize_launch.py;
                                exec bash'

# levine_blocked.csv
# gnome-terminal --tab -- bash -c 'ros2 run pure_pursuit pure_pursuit_node.py;
#                                 exec bash'

# gnome-terminal --tab -- bash -c 'ros2 run pure_pursuit interactive_node.py;
#                                 exec bash'

