#!/bin/bash

if ! dpkg -s xterm &> /dev/null; then
    sudo apt install xterm
fi

xterm -e "export TURTLEBOT3_MODEL=waffle; \
export GAZEBO_MODEL_PATH=$GAZEBO_MODEL_PATH:/opt/ros/foxy/share/turtlebot3_gazebo/models; \
ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py" &

xterm -e "ros2 launch slam_toolbox online_async_launch.py" &

xterm -e "ros2 launch nav2_bringup navigation_launch.py" &

xterm -e "rviz2" &

xterm -e "ros2 run teleop_twist_keyboard teleop_twist_keyboard" &
